ENVIRONMENT SETUP

In [ ]:
# Install required libraries
# transformers: model loading & training
# datasets: dataset handling
# evaluate: evaluation metrics
# torch: deep learning backend
!pip install -q transformers datasets accelerate sentencepiece evaluate scikit-learn pandas numpy torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.4 MB/s eta 0:00:00

In [ ]:
# Import core libraries
import pandas as pd
import numpy as np
import torch

# Hugging Face utilities
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    AutoModelForSeq2SeqLM,
    Trainer,
    TrainingArguments
)

LOAD AND PREPARE DATA

In [ ]:
# Load the two CounselChat CSV datasets
df1 = pd.read_csv("/content/20220401_counsel_chat.csv")
df2 = pd.read_csv("/content/counselchat-data.csv")

# Combine both datasets row-wise
# This keeps all question–answer pairs together
df = pd.concat([df1, df2], ignore_index=True)

#display first few rows of joint data
df.head()

,questionID,questionTitle,questionText,questionLink,topic,therapistInfo,therapistURL,answerText,upvotes,views,questionUrl,topics,therapistName,therapistUrl
0,0,Do I have too many issues for counseling?,I have so many issues to address. I have a his...,https://counselchat.com/questions/do-i-have-to...,depression,Jennifer MolinariHypnotherapist & Licensed Cou...,https://counselchat.com/therapists/jennifer-mo...,It is very common for people to have multiple ...,3,1971.0,NaN,NaN,NaN,NaN
1,0,Do I have too many issues for counseling?,I have so many issues to address. I have a his...,https://counselchat.com/questions/do-i-have-to...,depression,"Jason Lynch, MS, LMHC, LCAC, ADSIndividual & C...",https://counselchat.com/therapists/jason-lynch...,"I've never heard of someone having ""too many i...",2,386.0,NaN,NaN,NaN,NaN
2,0,Do I have too many issues for counseling?,I have so many issues to address. I have a his...,https://counselchat.com/questions/do-i-have-to...,depression,Shakeeta TorresFaith Based Mental Health Couns...,https://counselchat.com/therapists/shakeeta-to...,Absolutely not. I strongly recommending worki...,2,3071.0,NaN,NaN,NaN,NaN
3,0,Do I have too many issues for counseling?,I have so many issues to address. I have a his...,https://counselchat.com/questions/do-i-have-to...,depression,"Noorayne ChevalierMA, RP, CCC, CCAC, LLP (Mich...",https://counselchat.com/therapists/noorayne-ch...,Let me start by saying there are never too man...,2,2643.0,NaN,NaN,NaN,NaN
4,0,Do I have too many issues for counseling?,I have so many issues to address. I have a his...,https://counselchat.com/questions/do-i-have-to...,depression,"Toni Teixeira, LCSWYour road to healing begins...",https://counselchat.com/therapists/toni-teixei...,I just want to acknowledge you for the courage...,1,256.0,NaN,NaN,NaN,NaN

In [ ]:
# Standardise column names so both datasets share the same schema
df = df.rename(columns={
    "questionText": "question",
    "answerText": "answer"
})

# Retain only the columns required for the project
# These directly support the problem → advice modelling task
# Remove rows with missing values
df = df[["question", "answer"]].dropna()

# Remove duplicate question–answer pairs
df = df.drop_duplicates()

LENGTH-BASED FILTERING

In [ ]:
# Compute character length of questions and answers
# These helper columns are used only for filtering
df["question_len"] = df["question"].str.len()
df["answer_len"] = df["answer"].str.len()

# Remove outliers that are too long for transformer models
# This ensures stable training and concise advice generation
df = df[(df["question_len"] < 500) & (df["answer_len"] < 600)]

# Drop helper columns after filtering
df = df.reset_index(drop=True)

MENTAL HEALTH TEXT ANALYSIS MODEL

(BERT-based classifier)

In [ ]:
# We use a publicly available clinical BERT model
# This avoids gated access issues and is widely used in research
from transformers import AutoTokenizer, AutoModelForSequenceClassification
MODEL_NAME = "bert-base-uncased"

# Load tokenizer for the mental-health analysis model
mental_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Load model for sequence classification
# We use 2 labels as a simplified setup (e.g., distress vs non-distress)
mental_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Prepare Dataset for Mental Health Analysis

In [ ]:
# Tokenisation function for BERT-style models
def mental_tokenize(batch):
    return mental_tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

PREPARE DATA FOR MENTAL ANALYSIS

In [ ]:
# Create a dataset for classification

# Simple heuristic labeling instead of random labels
def label_text(text):
    if not isinstance(text, str):
        return 0

    distress_words = [
        "sad", "depressed", "anxious", "lonely",
        "stress", "overwhelmed", "hopeless",
        "tired", "cry", "worthless"
    ]

    text = text.lower()
    return 1 if any(word in text for word in distress_words) else 0


mental_df = pd.DataFrame({
    "text": df["question"],
    "label": df["question"].apply(label_text)
})
# Convert to Hugging Face Dataset format
mental_dataset = Dataset.from_pandas(mental_df)

# Apply tokenisation
mental_dataset = mental_dataset.map(mental_tokenize, batched=True)

# Split into training and validation sets
mental_dataset = mental_dataset.train_test_split(test_size=0.2)


# Training configuration
from transformers import TrainingArguments, Trainer

mental_args = TrainingArguments(
    output_dir="./mentalbert",
    eval_strategy="epoch",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    logging_steps=50,
    save_strategy="epoch",
    report_to="none"
)
# Create Trainer object

mental_trainer = Trainer(
    model=mental_model,
    args=mental_args,
    train_dataset=mental_dataset["train"],
    eval_dataset=mental_dataset["test"]
)

# Train the model
mental_trainer.train()


# SAVE MODEL
mental_trainer.save_model("./mentalbert")
mental_tokenizer.save_pretrained("./mentalbert")

Map:   0%|          | 0/1184 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./mentalbert/tokenizer_config.json', './mentalbert/tokenizer.json')

In [ ]:
# Convert question–answer pairs into instruction-based format
def format_flan(example):
    prompt = (
        "Provide empathetic, safe advice for the following concern:\n"
        f"{example['question']}"
    )
    return {
        "input_text": prompt,
        "target_text": example["answer"]
    }

# Apply formatting
flan_df = df.apply(format_flan, axis=1, result_type="expand")

In [ ]:
# Convert to Hugging Face Dataset
flan_dataset = Dataset.from_pandas(flan_df)

# Split into training and validation sets
flan_dataset = flan_dataset.train_test_split(test_size=0.1)

LOAD FLAN-T5 MODEL

In [ ]:
FLAN_MODEL = "google/flan-t5-small"

# Load tokenizer and model
flan_tokenizer = AutoTokenizer.from_pretrained(FLAN_MODEL)
flan_model = AutoModelForSeq2SeqLM.from_pretrained(FLAN_MODEL)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
def flan_tokenize(batch):

  # Tokenise inputs
    model_inputs = flan_tokenizer(
        batch["input_text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

    # Tokenise targets (labels)
    labels = flan_tokenizer(
        batch["target_text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# Apply tokenisation
tokenized_flan = flan_dataset.map(flan_tokenize, batched=True, remove_columns=flan_dataset["train"].column_names)

Map:   0%|          | 0/1065 [00:00<?, ? examples/s]

Map:   0%|          | 0/119 [00:00<?, ? examples/s]

TRAIN FLAN-T5

In [ ]:
# Training configuration for Flan-T5
flan_args = TrainingArguments(
    output_dir="./flan_t5",
    eval_strategy="epoch",
    learning_rate=2e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    save_strategy="epoch",
    logging_steps=50,
    report_to="none",
    fp16=torch.cuda.is_available()
)

In [ ]:
# Create Trainer for Flan-T5
flan_trainer = Trainer(
    model=flan_model,
    args=flan_args,
    train_dataset=tokenized_flan["train"],
    eval_dataset=tokenized_flan["test"]

)

In [ ]:
# Train Flan-T5 model
flan_trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=801, training_loss=5.467525442887781, metrics={'train_runtime': 8167.5042, 'train_samples_per_second': 0.391, 'train_steps_per_second': 0.098, 'total_flos': 296960081264640.0, 'train_loss': 5.467525442887781, 'epoch': 3.0})

In [ ]:
# Save fine-tuned Flan-T5 model
flan_model.save_pretrained("./flan_t5")
flan_tokenizer.save_pretrained("./flan_t5")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./flan_t5/tokenizer_config.json', './flan_t5/tokenizer.json')

INFERENCE PIPELINE

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

mental_model.to(device)
flan_model.to(device)

def classify(text):
    inputs = mental_tokenizer(text, return_tensors="pt", truncation=True, padding=True).to(device)
    outputs = mental_model(**inputs)

    probs = torch.softmax(outputs.logits, dim=1)
    distress_prob = probs[0][1].item()

    label = "Distress" if distress_prob > 0.5 else "No Distress"
    return label, distress_prob


def generate(text):
    prompt = f"Provide calm, supportive advice for a young person:\n{text}"

    inputs = flan_tokenizer(prompt, return_tensors="pt").to(device)

    outputs = flan_model.generate(
        **inputs,
        max_length=120,
        do_sample=True,
        temperature=0.7
    )

    return flan_tokenizer.decode(outputs[0], skip_special_tokens=True)


def full_pipeline(text):
    label, confidence = classify(text)
    advice = generate(text)

    return {
        "prediction": label,
        "confidence": confidence,
        "advice": advice
    }

In [ ]:
# Test the full pipeline
test_input = "I feel overwhelmed by school and like I am not good enough."

result = full_pipeline(test_input)

print(result)

{'prediction': 'Distress', 'confidence': 0.9990205764770508, 'advice': 'There may of it as when so an a and that is, your, oen of you, to just or as good when, in that more as with we take an for for more. you. in k that should can be by to go you is. This is of your , veys. it I as it is in you when and.hrr-ao to be at that jm on'}

In [ ]:
!pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=36332c12ed04c836d1479aaf49f595be6f413dedf24954053ea20f739f974ba4
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [ ]:
import evaluate

bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")

preds = []
refs = []

# Loop through first 50 samples
for i in range(50):
    question = df["question"].iloc[i]
    answer = df["answer"].iloc[i]

    out = full_pipeline(question)

    preds.append(out["advice"])
    refs.append([answer])  # BLEU expects list of references

# Compute metrics
bleu_score = bleu.compute(predictions=preds, references=refs)
rouge_score = rouge.compute(predictions=preds, references=[r[0] for r in refs])

print("BLEU:", bleu_score)
print("ROUGE:", rouge_score)

BLEU: {'bleu': 0.0, 'precisions': [0.2946837763519707, 0.006563525550867323, 0.00047961630695443646, 0.0], 'brevity_penalty': 0.497359687908736, 'length_ratio': 0.5887749595250944, 'translation_length': 2182, 'reference_length': 3706}
ROUGE: {'rouge1': np.float64(0.19552206350543322), 'rouge2': np.float64(0.004425621642052964), 'rougeL': np.float64(0.11104512500377023), 'rougeLsum': np.float64(0.11252911369333349)}

In [ ]:
import shutil

shutil.make_archive("mentalbert", 'zip', "./mentalbert")
shutil.make_archive("flan_t5", 'zip', "./flan_t5")

'/content/flan_t5.zip'

In [ ]:
from google.colab import files

files.download("mentalbert.zip")
files.download("flan_t5.zip")